#!/bin/zsh

eval `opam config env --switch=4.06.0+flambda`

cd `dirname $0`
BASEDIR=`pwd`

envset(){
  case $1 in
  theories/before) COQVER=orig; vfiles=(presburger.v extraction.v) ;;
  theories/after) COQVER=mod; vfiles=(presburger.v extraction.v) ;;
  theories/marray)
    COQVER=mod
    vfiles=(ordinal_ext.v core.v extraction_ocaml.v \
            union_find.v floyd_warshall.v quicksort.v)
  ;;
  theories/misc) COQVER=mod; vfiles=(mergesort.v extraction_ocaml.v) ;;
  esac

  MATHCOMP=$BASEDIR/math-comp-$COQVER/mathcomp
  REGULAR=$BASEDIR/regular-$COQVER
  COQPREFIX=$BASEDIR/coq-$COQVER
  COQBIN=$COQPREFIX/bin
  COQLIB="-I $MATHCOMP -R $MATHCOMP mathcomp -R $REGULAR regular"
}

export GREP_COLORS='ms=101:mc=01;31:sl=:cx=:fn=35:ln=32:bn=32:se=36'

puterr(){
  echo $1 >&2
  error=1
}

#### Proof Scripts

foreach dir (theories/before theories/after theories/marray theories/misc)
pushd $dir

  envset $dir
  error=

  for f in $vfiles; do
    tail -c 1 $f | grep -q . && puterr "$f: no newline at end of file"
    tail -n 1 $f | grep -qv . && puterr "$f: trailing empty line"
    grep --color=auto -H -n " * $" $f && error=1
  done

  [[ -n $error ]] && exit 1

  (echo $COQLIB; echo $vfiles) > _CoqProject

  make -j ${JOBS:-4} VFILES="$vfiles" PATH="$COQBIN:$PATH" COQLIBS="$COQLIB"

popd # theories/*
end

#### Benchmarks

pushd ocaml

  for f in before after; do
    echo "module Presburger = Presburger_$f;;" > def.ml
    ocamlbuild -build-dir _presburger_$f -libs unix \
      -tag 'optimize(3)' \
      -tag 'remove_unused_arguments' \
      -tag 'unbox_closures' \
      -tag 'inlining_report' \
      presburger_main.native
    ocamlbuild -build-dir _presburger_$f -libs unix -ocamlc ocamlcp presburger_main.byte
  done

  for f in matrix wuf quicksort floyd_warshall; do
    ocamlbuild -build-dir _$f -libs unix \
      -tag 'optimize(3)' \
      -tag 'remove_unused_arguments' \
      -tag 'unbox_closures' \
      -tag 'inlining_report' \
      ${f}_main.native
    ocamlbuild -build-dir _$f -libs unix -ocamlc ocamlcp ${f}_main.byte
  done

popd # ocaml
