#!/bin/zsh

eval `opam config env --switch=4.06.0+flambda`

cd `dirname $0`
BASEDIR=`pwd`
INIT_PATH=$PATH

yes_no_prompt(){
while true; do
  read "l?$1"
  case $l:l in
    yes) return 0;;
    no) return 1;;
    *) echo Pleas answer by YES or NO. ;;
  esac
done
}

envset(){
  case $1 in
  coq-orig|math-comp-orig|regular-orig) KIND=orig ;;
  coq-mod|math-comp-mod|regular-mod) KIND=mod ;;
  esac
  
  MATHCOMP=$BASEDIR/math-comp-$KIND/mathcomp
  export COQBIN=$BASEDIR/coq-$KIND/bin/
  export COQLIB=(-R $MATHCOMP mathcomp)
  export PATH=$COQBIN:$INIT_PATH
}

yes_no_prompt "Coq, MathComp and the regular language library will be rebuilt. Do you want to continue? [yes/no] " || exit 1

foreach dir (coq-orig coq-mod)
pushd $dir
  envset $dir
  ./configure -local -native-compiler yes -camlp5dir $(ocamlfind query camlp5)
  make archclean clean
  make -j 8 world byte
popd
end

foreach dir (math-comp-orig math-comp-mod)
pushd $dir/mathcomp
  envset $dir
  make clean
  make COQFLAGS="-q $COQLIB -debug -native-compiler" -j 8
    #ssreflect/all_ssreflect.vo fingroup/all_fingroup.vo algebra/all_algebra.vo
popd
end

[[ -f regular.tar.gz ]] || \
    wget -O regular.tar.gz \
    http://www.ps.uni-saarland.de/~doczkal/regular/ConstructiveRegularLanguages-2013-12-07.tgz

sha256sum -c <<EOT
41e33914b37d8b744a4deaa1ca3ac4fe392b29bfb57aca2e24e1777eb1f4dfd5  regular.tar.gz
EOT

foreach dir (regular-orig regular-mod)
mkdir -p $dir
pushd $dir
  envset $dir
  tar xzf ../regular.tar.gz
  patch -p1 < ../regular.patch
  coq_makefile -f Make -o Makefile
  make clean
  make COQFLAGS="-q -R . regular $COQLIB -debug -native-compiler" -j 8
popd
end
