#!/bin/zsh

echo 'module Presburger = Presburger_before;;' > def.ml
ocamlbuild -build-dir _before presburger_main.native

echo 'module Presburger = Presburger_after;;' > def.ml
ocamlbuild -build-dir _after presburger_main.native

ocamlbuild -build-dir _matrix matrix_main.native
#ocamlbuild -build-dir _matrix -ocamlc ocamlcp matrix_main.byte
